### ISSUE TITLE
1.0.0 and v1 release tag/branch

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/action-k3s-helm#10]
## Goals

1. To cut a 1.0.0 release to improve resolution how we version this github action
2. To automate the work allowing users to pin to v1 and v2 etc.

## How?

By using https://github.com/Actions-R-Us/actions-tagger it seems we solve everything.

> Keep your action versions up-to-date by automatically promoting a major tag (and optionally, a latest tag) each time a release is created.

## Example workflow

```yaml
name: Update release tags

on:
  release:
    types: [published, edited]

jobs:
  actions-tagger:
    runs-on: windows-latest
    steps:
      - uses: Actions-R-Us/actions-tagger@latest
        env:
          GITHUB_TOKEN: "${{ github.token }}"
        with:
          publish_latest_tag: true
```

## Discussion

__Go for 1.0.0?__
Would it be okay to cut the 1.0.0 release? I think we have surpassed the initial immaturities and would benefit from the improved resolution in how to communicate breaking changes etc using SemVer 2.

__Implementation__
I have opened #11, follwing a merge of that, we can just create a new GitHub release and everything is done.

__Branch vs tag?__
One can use branches and tags, I'm not 100% on what I think is best. I'm considering how GitHub's dependabot would work if someone pins `v1` as a branch or tag, and if someone pins `v1.2.3` as a branch or tag, and how it would react to that in general etc.
