### ISSUE TITLE
Docker and k8s 1.24 issue

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/action-k3s-helm#49]
It seems this doesn't go great with k8s 1.24...

```yaml
      - uses: jupyterhub/action-k3s-helm@v2
        with:
          k3s-channel: ${{ matrix.k3s-channel }}
          metrics-enabled: false
          traefik-enabled: false
          docker-enabled: true
```

`docker-enabled=true` doesn't seem to work with k8s 1.24 any more... Sigh, that may make us need to load images that we build for our k8s cluster to be able to access.

It seems that what fails is...

```
NAME                         DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE
daemonset.apps/calico-node   0         0         0       0            0           kubernetes.io/os=linux   5m14s
```

Why doesn't this daemonset desire to schedule a pod? Does a `--docker` based k3s 1.24 node not provide a `kubernetes.io/os=linux` label?

No, that is not it. Apparently there is no `node` at all when using `--docker` in k3s 1.24.

Ah, well, it seems that we can retain docker for k8s 1.24, but we need [this config](https://rancher.com/docs/rancher/v2.6/en/faq/dockershim/) it seems.

## Related
- About `--docker`: https://github.com/k3s-io/k3s/blob/9d7230496d131fe47485ce02b5697c57e1068a29/pkg/agent/config/config.go#L324-L326
- About --container-runtime-endpoint: https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/#agent-runtime
